{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "metadata": {},
   "outputs": [],
   "source": [
    "# This is an automation of code provided in book Tom Bäckström, Okko Räsänen, Abraham Zewoudie, Pablo Pérez Zarazaga, Liisa Koivusalo,\n",
    "# Sneha Das, Esteban Gómez Mellado, Mariem Bouafif Mansali, Daniel Ramos, Sudarsana Kadiri and Paavo Alku “Introduction to Speech\n",
    "# Processing”, 2nd Edition, 2022. URL: https://speechprocessingbook.aalto.fi, DOI: 10.5281/zenodo.6821775.\n",
    "\n",
    "# In order to use this code you need to have .csv file containing the time intervals for intended words or sentences for your analysis\n",
    "\n",
    "# Get the path to the desktop directory on macOS\n",
    "import os\n",
    "user_directory = os.path.join(os.path.expanduser('~'), '')\n",
    "os.chdir(user_directory)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "metadata": {},
   "outputs": [],
   "source": [
    "import matplotlib.pyplot as plt\n",
    "import pandas as pd\n",
    "import librosa\n",
    "import librosa.display\n",
    "import numpy as np\n",
    "from scipy.linalg import solve_toeplitz, toeplitz\n",
    "import scipy\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 7,
   "metadata": {},
   "outputs": [],
   "source": [
    "\n",
    "# Load the CSV file into a DataFrame\n",
    "input_csv_file = './Desktop/Folders/.csv'  # Replace with your CSV file path\n",
    "df = pd.read_csv(input_csv_file)\n",
    "\n",
    "# Load the raw audio file\n",
    "audio_file = './Desktop/Folders/.wav'  # Replace with your audio file path\n",
    "audio, sample_rate = librosa.load(audio_file, sr=None)\n",
    "\n",
    "subject = 'Erfan'\n",
    "output_directory = './Desktop/Folders/Frequency_plots/Formant/' + subject + '/'  # Specify the directory where you want to save the plots\n",
    "\n",
    "# Create the output directory if it doesn't exist\n",
    "os.makedirs(output_directory, exist_ok=True)\n",
    "counter = 0\n",
    "\n",
    "for index, row in df.iterrows():\n",
    "    counter = counter+1\n",
    "    word_name = row['word']\n",
    "    start_time = row['start']\n",
    "    end_time = row['end']\n",
    "    \n",
    "    # Convert start and end times to sample indices\n",
    "    start_sample = int(start_time * sample_rate)\n",
    "    end_sample = int(end_time * sample_rate)\n",
    "\n",
    "    # Extract the audio segment within the specified time interval\n",
    "    word_audio = audio[start_sample:end_sample]\n",
    "\n",
    "    window_length = len(word_audio)\n",
    "\n",
    "    windowing_function = np.sin(np.pi*np.arange(0.5,window_length,1)/window_length)**2\n",
    "    frequency_vector = np.linspace(0,sample_rate/2000,int(window_length/2+1))\n",
    "    signal_spectrum = np.abs(scipy.fft.rfft(word_audio*windowing_function)) \n",
    "\n",
    "\n",
    "    autocorrelation = scipy.fft.irfft(np.abs(scipy.fft.rfft(word_audio*windowing_function))**2) \n",
    "                                                                                                \n",
    "    lpc_order = int(sample_rate/1000 + 2)\n",
    "    u = np.zeros([lpc_order+1,1])\n",
    "    u[0]=1\n",
    "    lpc_model = solve_toeplitz(autocorrelation[0:lpc_order+1],u)\n",
    "    lpc_model /= lpc_model[0]\n",
    "    envelope_spectrum = np.abs(scipy.fft.rfft(lpc_model,window_length,axis=0))**-1\n",
    "    signal_spectrum = np.abs(scipy.fft.rfft(word_audio*windowing_function))\n",
    "    envelope_spectrum *= np.max(signal_spectrum)/np.max(envelope_spectrum)\n",
    "\n",
    "    # Find peaks of envelope\n",
    "    diff_envelope = np.diff(envelope_spectrum,axis=0)\n",
    "    sign_diff_envelope = np.sign(diff_envelope)\n",
    "    diff_sign_diff_envelope = np.diff(sign_diff_envelope,axis=0)\n",
    "    peak_indices = np.argwhere(diff_sign_diff_envelope[:,0] < 0)+1\n",
    "    peak_indices = peak_indices[0:5]\n",
    "\n",
    "    plt.figure(figsize=[12,4])\n",
    "\n",
    "    plt.subplot(121)\n",
    "    plt.plot(frequency_vector,20*np.log10(signal_spectrum),label='Spectrum')\n",
    "    plt.plot(frequency_vector,20*np.log10(envelope_spectrum),linewidth=3,label='Envelope')\n",
    "    plt.plot(frequency_vector[peak_indices],20*np.log10(envelope_spectrum[peak_indices,0]),marker='^',linestyle='',label='Peaks')\n",
    "    for k in range(len(peak_indices)): \n",
    "        x = frequency_vector[peak_indices[k]]\n",
    "        y = 20*np.log10(envelope_spectrum[peak_indices[k],0]) + 5\n",
    "        plt.text(x,y,'F' + str(k+1))    \n",
    "        plt.legend()\n",
    "        plt.title(str(word_name)+' - '+ subject +'  - \\nLog-magnitude spectrum and its envelope')\n",
    "        plt.xlabel('Frequency (kHz)')\n",
    "        plt.ylabel('Magnitude $20\\log_{10}|X_k|$')\n",
    "        ax = plt.axis()\n",
    "        ax = [ax[0], ax[1], ax[2], ax[3]+5]\n",
    "        plt.axis(ax)\n",
    "\n",
    "    plt.subplot(122)\n",
    "    plt.plot(frequency_vector,20*np.log10(signal_spectrum),label='Spectrum')\n",
    "    plt.plot(frequency_vector,20*np.log10(envelope_spectrum),linewidth=3,label='Envelope')\n",
    "    plt.plot(frequency_vector[peak_indices],20*np.log10(envelope_spectrum[peak_indices,0]),marker='^',linestyle='',label='Peaks')\n",
    "    for k in range(len(peak_indices)): \n",
    "        x = frequency_vector[peak_indices[k]]\n",
    "        y = 20*np.log10(envelope_spectrum[peak_indices[k],0]) + 5\n",
    "        if x < 8:  plt.text(x,y,'F' + str(k+1))    \n",
    "    plt.legend()\n",
    "    plt.title(str(word_name)+' - '+ subject +'  - \\nLog-magnitude spectrum zoomed to [0,8kHz]')\n",
    "    plt.xlabel('Frequency (kHz)')\n",
    "    plt.ylabel('Magnitude $20\\log_{10}|X_k|$ (dB)')\n",
    "    ax = [0, 8, ax[2], ax[3]+5]\n",
    "    plt.axis(ax)\n",
    "\n",
    "    plt.tight_layout()\n",
    "\n",
    "    figure_filename = os.path.join(output_directory, str(counter)+'_'+f'{word_name}.jpg')\n",
    "    plt.savefig(figure_filename, dpi=300)\n",
    "    plt.close() \n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3.9.7 ('base')",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.9.7"
  },
  "orig_nbformat": 4,
  "vscode": {
   "interpreter": {
    "hash": "f08e49717b89637f45c221cc312824aad954e4787a708f9902b4c6d1f314e1de"
   }
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
